/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/npc.glb
*/

import React, { useRef, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import useActions from "../hooks/useActions";
import { RapierRigidBody, RigidBody } from "@react-three/rapier";
import Hi from "./Hi";

export function NPC() {
  const [sayHi, setSayHi] = useState(false);
  const group = useRef();
  const rigidNPCRef = useRef<RapierRigidBody>(null);

  const { nodes, materials, animations }: any = useGLTF("/models/npc.glb");
  const { actions } = useAnimations(animations, group);
  useActions({ actions });
  function handleOnClick() {
    setSayHi(!sayHi);
  }
  return (
    <group ref={group} dispose={null} onClick={handleOnClick}>
      <RigidBody colliders={"hull"} ref={rigidNPCRef} type="fixed">
        <mesh position={[5, 2, 2]}>
          <cylinderGeometry args={[0.25, 0.25, 2.5]}></cylinderGeometry>
          <meshPhongMaterial transparent={true} opacity={0}></meshPhongMaterial>
        </mesh>
      </RigidBody>
      <group
        name="Armature"
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.015}
        position={[5, 1.3, 2]}
      >
        <primitive object={nodes.mixamorigHips} />
        <skinnedMesh
          name="Beta_Joints"
          geometry={nodes.Beta_Joints.geometry}
          material={materials.Beta_Joints_MAT1}
          skeleton={nodes.Beta_Joints.skeleton}
        />
        <skinnedMesh
          name="Beta_Surface"
          geometry={nodes.Beta_Surface.geometry}
          material={materials.Beta_HighLimbsGeoSG3}
          skeleton={nodes.Beta_Surface.skeleton}
        />
      </group>
      {sayHi && <Hi></Hi>}
    </group>
  );
}

useGLTF.preload("/models/npc.glb");
